### ISSUE TITLE
WinError 10013嘗試存取通訊端被拒絕，因為存取權限不足。

### ISSUE THREAD

**Issue by donagapegun** [TCCinTaiwan/TcTube#3]
ctypes.windll.shell32.IsUserAnAdmin()

**Comment by TCCinTaiwan** [comment]
Make sure you port 80 is available.
You can use **netstat -ban** to check which program using port 80.
if you have grep command, you can also use:
`netstat -ban | grep ":80.*LISTENING" -A1`
簡單說就去把有占用80Port的程式關掉
